# Generated by Django 5.2.5 on 2025-10-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_photo_created_at_photo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
